version: '3.8'

services:
  brocker:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379/tcp
    networks:
      - backendnetwork
    volumes:
      - brocker:/data/redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - backendnetwork
    restart: unless-stopped

  backend:
    volumes:
      - static:/static
    env_file:
      - ./backend/.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - brocker
    networks:
      - backendnetwork
    links:
      - db:db
      - brocker:brocker
  
  celery:
    build: ./backend
    command: celery -A e_comm3rce worker -l INFO
    env_file:
      - ./backend/.env.dev
    depends_on:
      - brocker
      - backend
      - db
    networks:
      - backendnetwork

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - backendnetwork


networks:
  backendnetwork:
    driver: bridge

volumes:
  brocker:
  db:
  static:
