version: '3.8'

services:
  redis:
    image: redis
    restart: unless-stopped
    hostname: redis
    ports:
      - 6379:6379/tcp
    volumes:
      - redis:/data/redis

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  backend:
    hostname: backend
    volumes:
      - static:/static
    env_file:
      - ./backend/.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["./entrypoint.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
  
  celery:
    hostname: celery
    build:
      context: ./backend
    command: celery -A e_comm3rce worker -l INFO
    env_file:
      - ./backend/.env.dev
    links:
      - redis:redis
    depends_on:
      - redis

  flower:
    build:
      context: ./backend
    hostname: flower
    command: celery -A e_comm3rce flower
    env_file:
      - ./backend/.env.dev
    links:
      - redis:redis
    depends_on:
      - redis
    ports:
      - 5555:5555


  nginx:
    hostname: nginx
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    links:
      - backend:backend
    depends_on:
      - backend

volumes:
  redis:
  db:
  static:
