# Generated by Django 4.2.2 on 2023-07-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Product category slug')),
                ('name', models.CharField(max_length=255, verbose_name='Product category name')),
            ],
            options={
                'verbose_name': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='SpecificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Specification category slug')),
                ('name', models.CharField(max_length=255, verbose_name='Specification category name')),
                ('measurement_unit', models.CharField(max_length=255, verbose_name='Unit of measurement')),
            ],
            options={
                'verbose_name': 'Specification categories',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.specificationcategory', verbose_name='Specification category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('description', models.TextField(verbose_name='Product description')),
                ('image', models.ImageField(upload_to='', verbose_name='Product image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is product available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='Product category')),
                ('specifications', models.ManyToManyField(related_name='products', to='products.specification', verbose_name='Product specifications')),
            ],
        ),
    ]
