# Generated by Django 4.2.2 on 2023-07-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='specificationcategory',
            options={'verbose_name': 'Specification category', 'verbose_name_plural': 'Specification categories'},
        ),
    ]
