# Generated by Django 4.2.2 on 2023-07-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_is_admin_user_is_staff'),
        ('products', '0005_alter_product_specifications_delete_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='List owner')),
            ],
            options={
                'verbose_name': 'Waiting list',
                'verbose_name_plural': 'Waiting lists',
            },
        ),
        migrations.CreateModel(
            name='WaitingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
                ('waiting_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waitings.waitinglist', verbose_name='List')),
            ],
            options={
                'verbose_name': 'Waiting product',
                'verbose_name_plural': 'Waiting products',
            },
        ),
    ]
