# Generated by Django 4.2.2 on 2023-07-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_specifications_delete_specification_and_more'),
        ('users', '0002_rename_is_admin_user_is_staff'),
        ('waitings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='users.customer', verbose_name='List owner'),
        ),
        migrations.AlterField(
            model_name='waitingproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_products', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='waitingproduct',
            name='waiting_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='waitings.waitinglist', verbose_name='List'),
        ),
    ]
