# Generated by Django 4.2.2 on 2023-07-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_specifications_delete_specification_and_more'),
        ('waitings', '0002_alter_waitinglist_owner_alter_waitingproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitingproduct',
            unique_together={('waiting_list', 'product')},
        ),
    ]
