# Generated by Django 4.2.2 on 2023-07-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_is_admin_user_is_staff'),
        ('products', '0005_alter_product_specifications_delete_specification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='List owner')),
            ],
            options={
                'verbose_name': 'Favorite list',
                'verbose_name_plural': 'Favorite lists',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.favoritelist', verbose_name='List')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Favorite product',
                'verbose_name_plural': 'Favorite products',
            },
        ),
    ]
