# Generated by Django 4.2.2 on 2023-07-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_specifications_delete_specification_and_more'),
        ('users', '0002_rename_is_admin_user_is_staff'),
        ('favorites', '0002_alter_favoritelist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list', to='users.customer', verbose_name='List owner'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='favorite_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='favorites.favoritelist', verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to='products.product', verbose_name='Product'),
        ),
    ]
