# Generated by Django 4.2.2 on 2023-07-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_alter_cartproduct_cart'),
        ('users', '0002_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('address', 'Address'), ('self_pickup', 'Self Pickup'), ('postal_office', 'Postal Office')], max_length=255, verbose_name='Delivery type')),
                ('address', models.CharField(max_length=255, verbose_name='Delivery address')),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('in_process', 'In process'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=255, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Order created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Order last updated')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Cart')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Order owner')),
            ],
        ),
    ]
