# Generated by Django 4.2.2 on 2023-07-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('in_process', 'In process'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=255, verbose_name='Status'),
        ),
    ]
