# Generated by Django 4.2.2 on 2023-07-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Specification category slug')),
                ('name', models.CharField(max_length=255, verbose_name='Specification category name')),
                ('measurement_unit', models.CharField(max_length=255, verbose_name='Unit of measurement')),
            ],
            options={
                'verbose_name': 'Specification category',
                'verbose_name_plural': 'Specification categories',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='specifications.specificationcategory', verbose_name='Specification category')),
            ],
        ),
    ]
