# Generated by Django 4.2.2 on 2023-07-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationcategory',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit of measurement'),
        ),
    ]
